### ISSUE TITLE
java.lang.NoClassDefFoundError in SCM CLI Client

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#576]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/576) by Manuel Recena Soto (Bitbucket: [recena](https://bitbucket.org/recena), GitHub: [recena](https://github.com/recena)).**

----------------------------------------

Hello,

I was trying last release of SCM Manager and I found this excepcion while I used **CLI Client**:

```
#!java

pegaso:target recena$ java -jar scm-cli-client-1.37-jar-with-dependencies.jar --user scmadmin --password scmadmin --server http://192.168.1.46/scm server-version
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
	at sonia.scm.url.RestUrlProvider.<init>(RestUrlProvider.java:79)
	at sonia.scm.url.UrlProviderFactory.createUrlProvider(UrlProviderFactory.java:88)
	at sonia.scm.client.JerseyClientProvider.createSession(JerseyClientProvider.java:119)
	at sonia.scm.client.JerseyClientProvider.createSession(JerseyClientProvider.java:62)
	at sonia.scm.client.ScmClient.createSession(ScmClient.java:82)
	at sonia.scm.cli.cmd.SubCommand.createSession(SubCommand.java:184)
	at sonia.scm.cli.cmd.ServerVersionSubCommand.run(ServerVersionSubCommand.java:53)
	at sonia.scm.cli.cmd.SubCommand.run(SubCommand.java:119)
	at sonia.scm.cli.App.run(App.java:164)
	at sonia.scm.cli.App.main(App.java:127)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

The same command works fine with 1.36 version.
